server:
  AppVersion: 1.0.0
  AppName: moviesApp
  AppHost: http://localhost/
  Port: :8000
  Mode: Development
  JwtSecretKey: secretkey
  PrivateKeyToken : LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRREw1OTMzb2NSL0UwMGYKWGFtV0hDWFQwUFc2WGR0VHd5czArUVNqTVVxbGthd3J4TE9oczM2bDIvdGw1dHNoajI1SVZqSndIcm9oOG5ZYwpYREdscUxWSHBtRnUzbHltZWhhd2xhVHh6NnBGVTZRQnlRT2J1ZVA2ajFEb0dMNGtvczVsM1RlSlN4d0s3UStQCmh2N0NMOHRsMW9UMzRRc3B2UCtWb1J6N2RGZjF2WmNCTGdZMHZXQmNlYnI1cE0xQWU0d0FyNGtDK2JZM0tVZ08KcVBBZjVmcEV1M0Vzc1ZobEVXRFN1cVhza0UyOWZyTmFXcGRiazFjekl2OVgrUWZSK1kyZ0llLzltdEpXcHpkWgozLzBkc1JuS2pLZ1VWMDlYRmdmc0Q5TmdsSGhackVIMU5xcWwwZlB1Y3NYZjMwNzdzRmR1TkRPSXFZMVJGZFJkCmR0M2txTU85QWdNQkFBRUNnZ0VBTlpZRzBGZ3o4bzFZL0VBNkhCZmpuUW5TT2hzR1U3bjd0ZDBuYWRlL1hVbXUKTElaeUNySElPOEJYRGcyZ1V1NkZ0ZjdwSEd3RzBIc09yUjlSY002b2JWNzlSZ3lyM3BoQk5FRHZheGovRDE4Twp2K1ZhekdjSzBjTXVLUUN2bjZNbGlNR2RJYmlhY3dpZnlVRlozQ0NCWEk4R3ZMbm9uQnh1TXAxM3AyR0k2Q3hsCmE5eU1mMDVGUFVpa05aVE1xZFhqUFBKeTNFaWYwOU4vNkU5VldPTGlWejJUTk5YZFI0VVM4Ulp1dzJCVkEvVTMKV3diSmp4MGwyNE03aExpT0Q1RE9XU3gwUGlXMDZ4R29TL1BQMlI2QVppb3hQUG8zdFRtSU5lZVpGWjVZTUhKQgowMytlOFROcmsxMHFNN3p1dVJKMG9Mb2VNVGdFa3dxR25GSU12WmZaQVFLQmdRRDRiV0I4bGFpd3hlVDVMbkdpCnRESTk4dFlOc1V6SHdXRUdtdjZzTkFsNWY1U05NSXNRQW5KRmZHTHI0YStIcGdISGlLZWtnV3k3ZVcxZXU5Y3YKMXN4dmZSamxZc2NNdWk3amFSRmJpVzA1TUsrUm9TU2thRVRORkhXTnpRZDJXb3IxLzgrQkhoQWk1K1E2VmlBawowVWg5cWFNRnlPTm9JL3hhK0FyMlBwS1FRUUtCZ1FEU0h4QU1SdG83cjhNZjk3OG1kMEs3NW42bTBJdk1YdDlJCm9rWklCVDdQSVdYdnROaThnc0I3NzF4RExkMjRpK1h0K0lWeEU4L2cwVS9hcXpQN0ZuZmVpT1p5Y3hVQ0k5OEEKZkdnaUVESFcvVFJyOGIzdWh1NHB6VDdRa0tHUlBobittSTZIcmpnbW9UUkE4QmpnUXpYMUNrL2lEcktwYXo1bQpzeUo5endOVWZRS0JnUUNINWZXUlVhRmRTblJ1cDZ4OE1BMEgvRzZDUVFwYWYvdmV6QzBpOExoNklZT1hGUVlOCnRQamo4QjZCSVEyUHJBMXZKTjlvUzNDNndidEZ4b1g1NG93bE5RN0lkUmVrYTdrNHFBSlp5N3pYT3ozZjhZSUUKK2hFaEN0OGZ1aGdwODIvdkVJaG4vcFVmTXpHVGhBZkRmRVVta1FUZ0pqdllmVThRU0g1ZXBHNHl3UUtCZ0h2TwpMNjk4SStRZE9OUmlMcS9rZjE2bGZpU2VKbkVCeVlCTGxTdWtZNUM1OWcwYU9zWkFLRmdkL2ZmYlU1UUVZak1vClJzQU0wMlI5RUJjZzN4em43VE1pNk4yd3IwVTJpNVFHdVhpd29CMHp6aXA0SXRnamlycjRvelZTc3RBWWprcHoKNnk5STJPN3g5dzc0S1VBaWVlMXE2UXlpYW1UbXVycmFlODB6SjV3bEFvR0JBT0R6ZG5SM1VrK0tPNm1URjRlRwpvK0c3Wi9GUmZWRWUreXZPYVJBSjlZL0JlaFIwd2pQT05sZ2d5T1B4Yzh4WWtrL2w1d1FqZU53NjNsSkxLRUJ1CnQ4cFlNRkxMMnl0MHRSWnFRTnlWL3JoYUtzTFdzRXE1N0JZQWI4Z1BZUUV6b3Z2Njh0TnA2bzVRYUhuV1pGeEUKVGFUd1B1cHJSMUJ2L2dSeTRwSldFWTg4Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  PublicKeyToken : LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5K2ZkOTZIRWZ4Tk5IMTJwbGh3bAowOUQxdWwzYlU4TXJOUGtFb3pGS3BaR3NLOFN6b2JOK3BkdjdaZWJiSVk5dVNGWXljQjY2SWZKMkhGd3hwYWkxClI2WmhidDVjcG5vV3NKV2s4YytxUlZPa0Fja0RtN25qK285UTZCaStKS0xPWmQwM2lVc2NDdTBQajRiK3dpL0wKWmRhRTkrRUxLYnovbGFFYyszUlg5YjJYQVM0R05MMWdYSG02K2FUTlFIdU1BSytKQXZtMk55bElEcWp3SCtYNgpSTHR4TExGWVpSRmcwcnFsN0pCTnZYNnpXbHFYVzVOWE15TC9WL2tIMGZtTm9DSHYvWnJTVnFjM1dkLzlIYkVaCnlveW9GRmRQVnhZSDdBL1RZSlI0V2F4QjlUYXFwZEh6N25MRjM5OU8rN0JYYmpRemlLbU5VUlhVWFhiZDVLakQKdlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t
  IDExpiration: 15m
  RefreshExpiratio: 168h
  ActivationTokenExpiratio: 10m
  PepperSecreKey: secretkey
  ReadTimeout: 30s
  WriteTimeout: 30s
  CtxDefaultTimeout: 25s
  CSRF: false
logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Formate: json
  Level: info
postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: abdo
  PostgresqlPassword: abdo
  PostgresqlDbname: moviesapp
  PostgresqlSslmode: false
  PgDriver: pgx
redis:
  RedisAddr: localhost:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  poolTimeout: 240s
  Password: "" 
  DB: 0
mail:
  host: sandbox.smtp.mailtrap.io
  port: 2525
  username: username
  password: password
  sender :  sender
  timeOut : 10s
cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true
limiter:
  RPS: 2
  Burst: 4
  Enabled: true
CORS:
  TrustedOrigins: 
    - http://127.0.0.1:8000
    - http://127.0.0.1:3000
