server:
  AppVersion: 1.0.0
  Port: :8000
  Mode: Development
  JwtSecretKey: secretkey
  PeperSecreKey: secretkey
  ReadTimeout: 30s
  WriteTimeout: 30s
  CtxDefaultTimeout: 25s
  CSRF: false
logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Formate: json
  Level: info
postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: abdo
  PostgresqlPassword: abdo
  PostgresqlDbname: moviesapp
  PostgresqlSslmode: false
  PgDriver: pgx
cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true
limiter:
  RPS: 2
  Burst: 4
  Enabled: true